# Generated by Django 4.2.1 on 2023-06-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraphe1', models.TextField()),
                ('birhday', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('phEmailone', models.CharField(max_length=100)),
                ('freelance', models.CharField(max_length=100)),
                ('paragraphe2', models.TextField()),
            ],
        ),
    ]
